version: '3'
services:
  # PHP Service
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: quan-ly-nhan-su
    container_name: quan-ly-nhan-su-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - quan-ly-nhan-su-network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: quan-ly-nhan-su-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - quan-ly-nhan-su-network

  # MySQL Service
  db:
    image: mysql:5.7
    container_name: quan-ly-nhan-su-db
    restart: unless-stopped
    ports:
      - 3307:3306  # Thay đổi từ 3306:3306 thành 3307:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/my.cnf
    networks:
      - quan-ly-nhan-su-network

networks:
  quan-ly-nhan-su-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
